language: node_js
node_js:
- 8.11.3
cache:
  directories:
  - node_modules
before_install:
- npm install hexo-cli -g
install:
- npm install
script:
- hexo clean
- hexo generate && gulp
#- gulp
after_script:
  - cd ./public
  - git init
  #github用户名
  - git config user.name "xqmGitHub"
  #github邮箱
  - git config user.email "xqmmai@gmail.com"
  - git add .
  - git commit -m "auto commit by TravisCI at `date +%Y%m%d`"
  # Github Pages
  - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  - git push --force --quiet "https://xqmcode:${CO_TOKEN}@${CO_REF}" master:master

branches:
  only:
  #这里替换你要监听的分支
  - hexo

env:
 global:
   # Github Pages(github仓库地址)
   - GH_REF: github.com/xqmgithub/xqmgithub.github.io.git
   # Coding Pages(coding仓库地址)
   - CO_REF: git.coding.net/xqmcode/xqmcode.git
   
# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
# https://docs.travis-ci.com/user/notifications/
notifications:
  email:
    - xqmmai@gmail.com
  on_success: change
  on_failure: always